<a href="https://colab.research.google.com/github/omerjamil13/Python-project/blob/main/Major.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/content/sample_data/salaries_by_college_major.csv")

In [ ]:
data.head(10)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM

In [ ]:
data.groupby("Undergraduate Major").mean()

<ipython-input-33-333c3f2e9080>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby("Undergraduate Major").mean()

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Undergraduate Major,,,,
Accounting,46000.0,77100.0,42200.0,152000.0
Aerospace Engineering,57700.0,101000.0,64300.0,161000.0
Agriculture,42600.0,71900.0,36300.0,150000.0
Anthropology,36800.0,61500.0,33800.0,138000.0
Architecture,41600.0,76800.0,50600.0,136000.0
Art History,35800.0,64900.0,28800.0,125000.0
Biology,38800.0,64800.0,36900.0,135000.0
Business Management,43000.0,72100.0,38800.0,147000.0
Chemical Engineering,63200.0,107000.0,71900.0,194000.0
Chemistry,42600.0,79900.0,45300.0,148000.0
Civil Engineering,53900.0,90500.0,63400.0,148000.0
Communications,38100.0,70000.0,37500.0,143000.0
Computer Engineering,61400.0,105000.0,66100.0,162000.0
Computer Science,55900.0,95500.0,56000.0,154000.0
Construction,53700.0,88900.0,56300.0,171000.0
Criminal Justice,35000.0,56300.0,32200.0,107000.0
Drama,35900.0,56900.0,36700.0,153000.0
Economics,50100.0,98600.0,50600.0,210000.0
Education,34900.0,52000.0,29300.0,102000.0
Electrical Engineering,60900.0,103000.0,69300.0,168000.0
English,38000.0,64700.0,33400.0,133000.0
Film,37900.0,68500.0,33900.0,136000.0
Finance,47900.0,88300.0,47200.0,195000.0
Forestry,39100.0,62600.0,41000.0,111000.0
Geography,41200.0,65500.0,40000.0,132000.0
Geology,43500.0,79500.0,45000.0,156000.0
Graphic Design,35700.0,59800.0,36000.0,112000.0
Health Care Administration,38800.0,60600.0,34600.0,101000.0
History,39200.0,71000.0,37000.0,149000.0
Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0
Industrial Engineering,57700.0,94700.0,57100.0,173000.0
Information Technology (IT),49100.0,74800.0,44500.0,129000.0
Interior Design,36100.0,53200.0,35700.0,107000.0
International Relations,40900.0,80900.0,38200.0,157000.0
Journalism,35600.0,66700.0,38400.0,145000.0
Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0
Marketing,40800.0,79600.0,42100.0,175000.0
Math,45400.0,92400.0,45200.0,183000.0
Mechanical Engineering,57900.0,93600.0,63700.0,163000.0
Music,35900.0,55000.0,26700.0,134000.0
Nursing,54200.0,67000.0,47600.0,98300.0
Nutrition,39900.0,55300.0,33900.0,99200.0
Philosophy,39900.0,81200.0,35500.0,168000.0
Physician Assistant,74300.0,91700.0,66400.0,124000.0
Physics,50300.0,97300.0,56000.0,178000.0
Political Science,40800.0,78200.0,41200.0,168000.0
Psychology,35900.0,60400.0,31600.0,127000.0
Religion,34100.0,52000.0,29700.0,96400.0
Sociology,36500.0,58200.0,30700.0,118000.0
Source: PayScale Inc.,NaN,NaN,NaN,NaN
Spanish,34000.0,53100.0,31000.0,96400.0

In [ ]:
data.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [ ]:
data.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [ ]:
clean_data = data.dropna()
clean_data.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [ ]:
#Highest mid career
clean_data.loc[8]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object

In [ ]:
#Lowest starting salary
clean_data.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

In [ ]:
#Lowest mid career
clean_data.loc[18]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [ ]:
spread = clean_data["Mid-Career 90th Percentile Salary"] - clean_data["Mid-Career 10th Percentile Salary"]
clean_data.insert(1,"Spread", spread)
print(clean_data.head(10))

     Undergraduate Major    Spread  Starting Median Salary  \
0             Accounting  109800.0                 46000.0
1  Aerospace Engineering   96700.0                 57700.0
2            Agriculture  113700.0                 42600.0
3           Anthropology  104200.0                 36800.0
4           Architecture   85400.0                 41600.0
5            Art History   96200.0                 35800.0
6                Biology   98100.0                 38800.0
7    Business Management  108200.0                 43000.0
8   Chemical Engineering  122100.0                 63200.0
9              Chemistry  102700.0                 42600.0

   Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
0                   77100.0                            42200.0
1                  101000.0                            64300.0
2                   71900.0                            36300.0
3                   61500.0                            33800.0
4                   76800.0                            50600.0
5                   64900.0                            28800.0
6                   64800.0                            36900.0
7                   72100.0                            38800.0
8                  107000.0                            71900.0
9                   79900.0                            45300.0

   Mid-Career 90th Percentile Salary     Group
0                           152000.0  Business
1                           161000.0      STEM
2                           150000.0  Business
3                           138000.0      HASS
4                           136000.0  Business
5                           125000.0      HASS
6                           135000.0      STEM
7                           147000.0  Business
8                           194000.0      STEM
9                           148000.0      STEM

In [ ]:
clean_data.loc[40]

Undergraduate Major                   Nursing
Spread                                50700.0
Starting Median Salary                54200.0
Mid-Career Median Salary              67000.0
Mid-Career 10th Percentile Salary     47600.0
Mid-Career 90th Percentile Salary     98300.0
Group                                Business
Name: 40, dtype: object

In [ ]:
clean_data.sort_values("Mid-Career 90th Percentile Salary", ascending=False)

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM
36,Marketing,132900.0,40800.0,79600.0,42100.0,175000.0,Business
30,Industrial Engineering,115900.0,57700.0,94700.0,57100.0,173000.0,STEM
14,Construction,114700.0,53700.0,88900.0,56300.0,171000.0,Business
45,Political Science,126800.0,40800.0,78200.0,41200.0,168000.0,HASS
42,Philosophy,132500.0,39900.0,81200.0,35500.0,168000.0,HASS
19,Electrical Engineering,98700.0,60900.0,103000.0,69300.0,168000.0,STEM
38,Mechanical Engineering,99300.0,57900.0,93600.0,63700.0,163000.0,STEM
12,Computer Engineering,95900.0,61400.0,105000.0,66100.0,162000.0,STEM
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
33,International Relations,118800.0,40900.0,80900.0,38200.0,157000.0,HASS
25,Geology,111000.0,43500.0,79500.0,45000.0,156000.0,STEM
13,Computer Science,98000.0,55900.0,95500.0,56000.0,154000.0,STEM
16,Drama,116300.0,35900.0,56900.0,36700.0,153000.0,HASS
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
28,History,112000.0,39200.0,71000.0,37000.0,149000.0,HASS
10,Civil Engineering,84600.0,53900.0,90500.0,63400.0,148000.0,STEM
9,Chemistry,102700.0,42600.0,79900.0,45300.0,148000.0,STEM
7,Business Management,108200.0,43000.0,72100.0,38800.0,147000.0,Business
35,Management Information Systems (MIS),100700.0,49200.0,82300.0,45300.0,146000.0,STEM
34,Journalism,106600.0,35600.0,66700.0,38400.0,145000.0,HASS
11,Communications,105500.0,38100.0,70000.0,37500.0,143000.0,HASS
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
21,Film,102100.0,37900.0,68500.0,33900.0,136000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business
6,Biology,98100.0,38800.0,64800.0,36900.0,135000.0,STEM
39,Music,107300.0,35900.0,55000.0,26700.0,134000.0,HASS
20,English,99600.0,38000.0,64700.0,33400.0,133000.0,HASS
24,Geography,92000.0,41200.0,65500.0,40000.0,132000.0,HASS
31,Information Technology (IT),84500.0,49100.0,74800.0,44500.0,129000.0,STEM
46,Psychology,95400.0,35900.0,60400.0,31600.0,127000.0,HASS
5,Art History,96200.0,35800.0,64900.0,28800.0,125000.0,HASS
29,Hospitality & Tourism,88500.0,37800.0,57500.0,35500.0,124000.0,Business
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM
48,Sociology,87300.0,36500.0,58200.0,30700.0,118000.0,HASS
26,Graphic Design,76000.0,35700.0,59800.0,36000.0,112000.0,HASS
23,Forestry,70000.0,39100.0,62600.0,41000.0,111000.0,Business
32,Interior Design,71300.0,36100.0,53200.0,35700.0,107000.0,HASS
15,Criminal Justice,74800.0,35000.0,56300.0,32200.0,107000.0,HASS
18,Education,72700.0,34900.0,52000.0,29300.0,102000.0,HASS
27,Health Care Administration,66400.0,38800.0,60600.0,34600.0,101000.0,Business
41,Nutrition,65300.0,39900.0,55300.0,33900.0,99200.0,HASS
40,Nursing,50700.0,54200.0,67000.0,47600.0,98300.0,Business
47,Religion,66700.0,34100.0,52000.0,29700.0,96400.0,HASS
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
clean_data.groupby("Group").mean()

<ipython-input-62-ecee10614a53>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  clean_data.groupby("Group").mean()

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"

In [ ]:
clean_data.shape

(50, 7)